### PR TITLE
Example of removing sidebar on mobile

### PR DESCRIPTION
**Pull request by aidos**
As asked about on HN, here's a model for how you can remove the sidebar on mobile. I'm not saying it's a good idea (and I haven't tested locally because I couldn't get it running). But if you wanted to try it / discuss it, then it's a start.

### CODE REVIEW

**Comment by zzzeek** [comment]
thanks for this, I will check it out!!!

**Comment by zzzeek** [comment]
well it certainly helps,  thanks!  it is still kind of mystifying what my browser (chrome on android) does with font sizes.  I put up a copy of the site and removed all the font sizes and downgraded every font to generic "sans-serif" "fixed" etc. and it still uses dramatically different font sizes for different page elements.

**Comment by aidos** [comment]
You free to jump on a call to show me some of the issues and I'll see what I can do? You can find my email on HN (aidos).

**Comment by zzzeek** [comment]
Hi Aidan -

thanks for the offer.  it looks like when you do mobile, you have to make sure all the menus and things that only scale on more pixels simply don't appear.   I tried a test site and removing all the custom fonts and making sure there were no font pixel sizes anywhere, and still we get vastly different text sizes in different spaces and it seems to be related to a decision the browser makes about how much text it needs to fit in the secton.   see attached screenshots.     this leads me to believe a full mobile experience would be a large effort.



Screenshot_20210225-132818
Screenshot_20210225-133921

**Comment by aidos** [comment]
I think probably the best approach here is to help me get this up and running locally so I can make some more meaningful contributions. Then I can chip away at it when I get a spare moment.

Do you have a list of steps somewhere to build the documentation from scratch?

**Comment by zzzeek** [comment]
well the basic docs are a sphinx build, which is fairly straightforward.  you can browse them on a file browser, and that might be enough.

for this, the steps from scratch are as follows:

```
$ git clone https://github.com/sqlalchemy/sqlalchemy/
$ virtualenv .venv
$ source .venv/bin/activate
$ cd sqlalchemy/doc/build/
$ pip install sphinx
$ pip install -r requirements.txt
$ make html


```



building out the whole website, which provides the whole headers/footers and maybe some font tweaks, is a less friendly endeavor but I could show you that also.

**Comment by aidos** [comment]
That's got me up and running and I think I've found my way around now. When I next get a moment, I'll have a play to see if I can make it work a little better.

**Comment by zzzeek** [comment]
thanks for helping!

**Pull request merged**
