### PR TITLE
Add dialect version table support

### PR DESCRIPTION
**Pull request by CaselIT**
Extend the dialect directive to include the supported versions.

These will the used to generate a table in each dialect page like the following
image

In the dialect index page it will also generate a summary table like the following
image

This table is generated using a new `dialect-table` directive

See also https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2585 that uses the new features of the dialect directive

### CODE REVIEW

**Comment by jvanasco** [comment]
Very nice, @CaselIT !

**Comment by zzzeek** [comment]
wow this all works?  amazing!

**Comment by CaselIT** [comment]
it seems so.

I forgot to bump the version

**Comment by CaselIT** [comment]
Once you understand a bit [the example](https://www.sphinx-doc.org/en/master/development/tutorials/todo.html
) by sphinx, it's not too hard to do.

**Pull request merged**
